title: Juan Luis Gastaldi
description: I am a philosopher of sciences working at ETH ZÃ¼rich
show_downloads: true
google_analytics:
# theme: jekyll-theme-cayman

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

github:
  home: ./
  news: ./p.news.html
  publications: ./p.publications.html
  projects: ./p.projects.html
  teaching: ./p.teaching.html
  contact: ./p.contact.html

img:
  photo: ./assets/img/G.jpg
  background: ./assets/img/heatmap.jpg